### ISSUE TITLE
SolidOS Web App incorrectly changes the URL path

### ISSUE THREAD

**Issue by renyuneyun** [SolidOS/solidos#165]
When testing the behaviour of SolidOS/mashlib, I tried to use the [SolidOS databrowser app](https://solidos.github.io/mashlib/dist/browse.html), which is linked in the README of this repo.

The page loads successfully, and trying to fetch server's/pod's content works correctly. However, after attempting to log-in, the redirect goes to an unexpected destination, resulting in 404.

Checking the URL, it came from the app itself, to a different path:

- From `https://solidos.github.io/mashlib/dist/browse.html`
- To `https://solidos.github.io/mashlib/dist/MY_SERVER?uri=MY_USER_POD&code=SOME_CODE&state=SOME_STATE_CODE`

In fact, after putting the pod address to the "Viewing" field and clicking "go", the page's URL changes already:

- `https://solidos.github.io/mashlib/dist/MY_SERVER?uri=MY_USER_POD`

(Some fields are replaced with CAPITAL_WORDS.)

Shouldn't the path be kept constant, while only the query changes?

**Comment by jeff-zucker** [comment]
I can not reproduce this behavior.  Can you tell me the exact steps you too?  Also, please tell me what server the pod is on and try clearing your cache, and cookies.

**Comment by jeff-zucker** [comment]
Also - do you perhaps have other pages logged in on different tabs?

**Comment by renyuneyun** [comment]
Thanks @jeff-zucker . You are probably right that I need to clear cache first. Trying it in private windows and this does not exist.
For how long will the cache be kept in the browser? I haven't been using the web app for at least a month.

I'll close this issue.
