### ISSUE TITLE
Camera view is hidden behind the QR code 

### ISSUE THREAD

**Issue by phochste** [SolidOS/solidos#174]
The camera view gets hidden behind the QR code on the user profile page when starting a chat.

Browser:

Vivaldi | 5.3.2679.68 (Stable channel) (x86_64)

Steps taken:

- Login into the test pod
- Visit https://hochstenbach.solidcommunity.net:8443/profile/card#me
- Start a new chat
- Click on the camera

Expected:

- See a camera window

Result:

- Camera window that is hidden behind the use QR code
![Screenshot 2022-07-21 at 11 00 23](https://user-images.githubusercontent.com/66416/180174550-91a0e6a1-5d27-450e-9e6f-ced36549c8b1.png)

**Comment by phochste** [comment]
Same happens when opening the 'setting' menu in the chat.

![Screenshot 2022-07-21 at 11 02 36](https://user-images.githubusercontent.com/66416/180174947-c355e6b3-93a6-4d25-8545-5b525f5bc5a2.png)

**Comment by bourgeoa** [comment]
I do not have the issue anymore. seems to have been resolved
