### ISSUE TITLE
Add instance containers to Your Stuff

### ISSUE THREAD

**Issue by timbl** [SolidOS/solidos#179]
Currently individual instances of things, like Trackers and Chats, show up in the "Your Stuff" lists.  But collections of things, like a folder of Movies or Recipes do not show up.  
The type index data looks like for example 
```

:05bcf345-9c87-409b-9558-14e679421da5
    a solid:TypeRegistration;
    solid:forClass schem:Movie;
    solid:instanceContainer mov: .
:7af1631c-05c8-472f-b883-e3434e030ba0
    a solid:TypeRegistration;
    solid:forClass schem:Recipe;
    solid:instanceContainer coo: .
:c6a676bc-935d-4eb7-8fd1-69b5ecbd50f4
    a solid:TypeRegistration;
    solid:forClass schem:WatchAction;
    solid:instanceContainer mov: .

```

**Comment by bourgeoa** [comment]
I think there is an issue, the content of the container is listed, I suppose it should be the container.

![image](https://user-images.githubusercontent.com/2218470/190186340-8d54fb34-8651-4b66-8424-5e5bedd4385f.png)

![image](https://user-images.githubusercontent.com/2218470/190186807-3c969ae0-163b-4b73-a3e1-5d4919223ccf.png)

**Comment by bourgeoa** [comment]
closed with https://github.com/SolidOS/solid-logic/issues/54
