### ISSUE TITLE
multi-select does not work anymore in user's preferences

### ISSUE THREAD

**Issue by bourgeoa** [SolidOS/solidos#180]
On the NSS test server the multi-select function is broken in user's preferences.

**Comment by jeff-zucker** [comment]
Could you be more specific?  I can change the user role in the select.  I can select & deselect trusted apps.  What is broken?

**Comment by bourgeoa** [comment]
You cannot anymore select both user roles. Multi select

**Comment by jeff-zucker** [comment]
I can do that fine in chrome.

**Comment by jeff-zucker** [comment]
Oh, sorry, I missed that you said the test server.  Right, it is not broken so much as missing.  There needs to be a size attribute of 2  on the select element.
