### ISSUE TITLE
"authorize null" because there is a null origin from the out-of-browser login

### ISSUE THREAD

**Issue by timea-solid** [SolidOS/solidos#184]
An interesting usage of SolidOS seems to not work properly. Authorization related. 
see thread: https://gitter.im/solid/solidos?at=63236a8d458f823ce084af48

Also followup: https://gitter.im/solid/solidos?at=63248e7c72ad51741fe371f8

**Comment by jeff-zucker** [comment]
We already have an issue on this.  It is not specific to SolidOS.  https://github.com/SolidOS/solidos/issues/183#issuecomment-1257074653
