### ISSUE TITLE
Authentication error: Mismatching redirect uri

### ISSUE THREAD

**Issue by josephguillaume** [SolidOS/solidos#200]
Using solidcommunity.net with Node Solid Server 5.7.4 (mashlib 1.8.5)

Not sure which component this behaviour comes from:
- Visit a page, e.g. https://josephguillaume.solidcommunity.net
- Login
- Refresh the page or paste in a url to another page

As intended, solidos tries to login again.
Error occurs in the authorize step:

`https://solidcommunity.net/authorize?client_id=eaabc2c1e05114db2327794f34f54f56&redirect_uri=https%3A%2F%2Fjosephguillaume.solidcommunity.net%2F%3Fstate%3D2d8634d1ec034756882cb299fc60ef38&response_type=code&scope=openid%20offline_access%20webid&state=176ab065bec548dbaf188b765d4f28d2&code_challenge=IJAMzeDfoBcwdWIj0pvVdmSVvtjQdGz_f2bPO-3auvY&code_challenge_method=S256&prompt=none&response_mode=query`

`{"error":"invalid_request","error_description":"Mismatching redirect uri"}`

The error seems to be due to the added state parameter in the redirect URI.

**Comment by Homegnolia** [comment]
I experience the same thing : 
Once I connect, I access my home page, and sometimes I can create a new folder and a new subfolder, plus a tracker or file. But then, when I want to open it, there's a redirection which seems wrong  and the following message appears : 
`{"error":"invalid_request","error_description":"Mismatching redirect uri"}`
Then I can't reconnect or disconnect. I have to empty cache and delete cookies in order to be abble to try login in again.

**Comment by josephguillaume** [comment]
Fixed in mashlib 1.8.8 through the issues mentioned above. Thanks @bourgeoa !

**Comment by bourgeoa** [comment]
Yes there is only one mashlib build.
Could you experiment with some detail so I could try to reproduce.

**Comment by renyuneyun** [comment]
> Could you experiment with some detail so I could try to reproduce.

I tried to do, but did not manage so.

In particular, I cannot get rid of this error message now. I do not have cookies nor local storage for Mashlib (https://solidos.github.io/mashlib/dist/browse.html) and solidcommunity.net. But I do get this issue every time now.

A plausible guess is: I log-in with solidcommunity.net first with Mashlib; then log-out; then log-in with another Solid account (my own CSS host); then log-out; then trying to log-in to solidcommunity.net -- problem appeared.

Not sure though. Will try more.
