### ISSUE TITLE
Profile/Preferences not editable even though logged in

### ISSUE THREAD

**Issue by DoctorBud** [SolidOS/solidos#29]
This was initially reported in https://gitter.im/solid/solidcommunity.net?at=5ff6885e3567d7393d48eb4a

 I logged into my POD at https://doctorbud.solidcommunity.net successfully, but when I try to  do anything with my Profile... I get an in-page error message:
> Your profile https://doctorbud.solidcommunity.net/profile/card is not editable, so we cannot do much here

and if I try to click on `Your Storage` or various other features, I get an actual popup dialog that says:
> Strange - you are not authenticated (properly logged in) to read preference file.

I reloaded the page and tried logging out and in again, but had the same result.

At the suggestion of @jeff-zucker , I clicked on the Solid icon in the upper left, which cleared the error state and allowed me to proceed.

I'm putting this issue here for tracking purposes. I cannot duplicate this error currently.

**Comment by DoctorBud** [comment]
Perhaps another clue. I had the same issue while *logged into* https://doctorbud.solidcommunity.net and trying to *view* https://solidos.solidcommunity.net, I get the popup dialog saying

> Strange - you are not authenticated (properly logged in) to read preference file.

Logging out and back in to https://doctorbud.solidcommunity.net via the https://solidos.solidcommunity.net login page made everything work as expected again.

However, when I then tried to use the `Edit Your Profile` command from the drop-down menu under my avatar, I ended up back in the *bad state*. This workflow of using `Edit Your Profile` from the menu while not on the same host that login occurred on seems to be the root of the problem that leads to chaos.

One other part of this chaos is that attempting to log into https://doctorbud.solidcommunity.net via the https://solidos.solidcommunity.net `Login` workflow now results in a `Too Many Redirects` error.

**Comment by angelo-v** [comment]
another person having troubles with that: https://forum.solidproject.org/t/error-your-profile-is-not-editable/4149/2

**Comment by jeff-zucker** [comment]
This is not a solution to the problem but a possible work-around.  We could have a button on the "you're not logged in" screen that says "If you believe this message is in error, click here to erase your browser cache".

**Comment by jeff-zucker** [comment]
It would at least cut down on traffic in the forum :-)

**Comment by timbl** [comment]
I suspect the underlying problem here may be this rdflib.js one: https://github.com/linkeddata/rdflib.js/issues/441

**Comment by theRealImy** [comment]
I currently have this issue on my local installation of SolidOS: mashlib 1.7.22, NSS 5.6.24 (not using multi-user and all default configs)
I tried twice to setup my local env from scratch with:
git clone solidos
npm run setup
npm run start or npm run watch
The line of code where it should return that the profile is editable is: https://github.com/solid/solid-panes/blob/033f48f8987364cb131455b13e8b0637da95a5ab/src/profile/editProfile.view.ts#L97
it uses the editable function from update-manager.

**Comment by timea-solid** [comment]
duplicate with https://github.com/SolidOS/solidos/issues/138 ?
