### ISSUE TITLE
Why a map header ? Issue when used in CSS

### ISSUE THREAD

**Issue by bourgeoa** [SolidOS/solidos#79]
https://gitter.im/solid/solidos?at=617c0e3d38377967f47f882c

**Comment by bourgeoa** [comment]
Trinpod needs the same https://gitter.im/solid/app-development?at=61a6af75cd3f06175de394c4

**Comment by theRealImy** [comment]
maybe related: https://github.com/solid/mashlib/issues/133

**Comment by timea-solid** [comment]
https://github.com/linkeddata/rdflib.js/issues/585
